### ISSUE TITLE
documentation on how to do updates 

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#32]
I would like to update to the newest version. There is no documentation on what's the best way to do that.

I have tried
> conda update –c acme processflow

This did not work, I got an error (documented in https://github.com/ACME-Climate/acme_processflow/issues/31 ) 

I then tried install it with
> conda create -n workflow -c acme -c conda-forge -c uvcdat  -c lukasz processflow

I got: 
CondaValueError: prefix already exists: /export/mccoy20/anaconda2/envs/workflow

I then removed /export/mccoy20/anaconda2/envs/workflow
and repeat 'conda create'. 

It would be nice to have a way to clean up the install and the reinstall only what's needed, maybe that's what update is doing. Can't say because it did not work.

----------------
Adding after trying to run again:
After the 'conda create ..' competed successfully, I then tried to run processflow again and got an error:

bash-4.1$>  source activate workflow
(workflow) bash-4.1$>  processflow.py -c run.cfg
Traceback (most recent call last):
  File "/export/mccoy20/anaconda2/envs/workflow/bin/processflow.py", line 4, in <module>
    __import__('pkg_resources').run_script('acme-processflow==0.3.14', 'processflow.py')
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/acme_processflow-0.3.14-py2.7.egg/EGG-INFO/scripts/processflow.py", line 987, in <module>
    
  File "build/bdist.linux-x86_64/egg/lib/setup.py", line 194, in setup
  File "build/bdist.linux-x86_64/egg/lib/util.py", line 662, in check_for_inplace_data
KeyError: '46-4'
(workflow) bash-4.1$

**Comment by sterlingbaldwin** [comment]
I dont know why, but conda update doesnt work for me with just about any package. I think this is an issue with conda itself. When I do updates, just do
```
conda install -c acme processflow
```
which will install the latest version.
