### ISSUE TITLE
acme_diags did not produce output, waiting for user input on UVCDAT_ANONYMOUS_LOG ?

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#37]
The acme_diags did not produce output in the latest run on 9/22 (/p/cscratch/acme/mccoy20/test_2017-09-14-Chris)

It seems that it may be waiting for user input, here is the output of acme_diag_set_1980_1984_8d193.err
----
[mccoy20@acme1 run_scripts]$ more acme_diag_set_1980_1984_8d193.err
Traceback (most recent call last):
  ...
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/cdms2/__init__.py", line 6, in <module>
    cdat_info.pingPCMDIdb("cdat", "cdms2")  # noqa
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 205, in pingP
CMDIdb
    askAnonymous(val)
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/cdat_info/cdat_info.py", line 164, in askAn
onymous
    "(you can also set the environment variable UVCDAT_ANONYMOUS_LOG to yes or no)? [yes]/no: ")
EOFError: EOF when reading a line
---

**Comment by zshaheen** [comment]
@mccoy20 @sterlingbaldwin I think Renata's correct, I've had this issue before. Just set the environmental variable beforehand. So either `export UVCDAT_ANONYMOUS_LOG=False` or `export UVCDAT_ANONYMOUS_LOG=True`.

**Comment by sterlingbaldwin** [comment]
Fixed in the new nightly.
