### ISSUE TITLE
Can't start processflow

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#44]
directory /export/mccoy20/pRen/test_2017-09-14-Qi

bash-4.1$ conda install -c acme/label/nightly processflow
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /export/mccoy20/anaconda2/envs/workflow:
#
processflow               0.3.17                    devel    acme/label/nightly

--
bash-4.1$ processflow.py -c run.cfg
Traceback (most recent call last):
  File "/export/mccoy20/anaconda2/envs/workflow/bin/processflow.py", line 4, in <module>
    __import__('pkg_resources').run_script('acme-processflow==0.3.17', 'processflow.py')
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/site-packages/acme_processflow-0.3.17-py2.7.egg/EGG-INFO/scripts/processflow.py", line 1043, in <module>
    
  File "build/bdist.linux-x86_64/egg/lib/setup.py", line 199, in setup
  File "build/bdist.linux-x86_64/egg/lib/util.py", line 608, in check_for_inplace_data
KeyError: '46-4'

**Comment by sterlingbaldwin** [comment]
The lowest number year of that simulation is 20170628.POP_MG2.A_WCYCL1850.ne30_g16.edison.cam.h0.0041-01.nc, but your config is asking for year 0001. That said, there's obviously a bug in how the file table is being setup. Im going to have to completely refactor how I manage files for the short term archiving, so this issue should hopefully be resolved by that. In the mean time, try setting simulation_start_year to 41.
